### ISSUE TITLE
Can't get license-key from Secrets Manager via SSM Parameter store

### ISSUE THREAD

**Issue by kaojiri** [newrelic/nri-ecs#10]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

I tried this feature([implemeted by cloud formation](https://docs.newrelic.com/docs/integrations/elastic-container-service-integration/installation/install-ecs-integration#cloud-formation-install)) however a error occurred below when I started task ...

```
Fetching secret data from SSM Parameter Store in ap-northeast-1: AccessDeniedException: 
User: arn:aws:sts::xxxxxxxxxxxx:assumed-role/NewRelicECSIntegration-Ne-NewRelicECSTaskExecution-xxxxxxxxxxxx/xxxxxxxxxxxx 
is not authorized to perform: ssm:GetParameters on resource: arn:aws:ssm:ap-northeast-1:xxxxxxxxxxxx:parameter/aws/reference/secretsmanager/NewRelicLicenseKeySecret-xxxxxxxxxxxx 
status code: 400, request id: xxxxxxxxxxxxxx
```

## Description
[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT share sensitive information, whether personal, proprietary, or otherwise! )

Same above.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen. )

Task is started and collect container's data to New Relic.

## [Troubleshooting](https://docs.newrelic.com/docs/integrations/host-integrations/troubleshooting/not-seeing-host-integration-data) or [NR Diag](https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/troubleshooting/new-relic-diagnostics) results
[NOTE]: # ( Provide any other relevant log data. )
[TIP]:  # ( Scrub logs and diagnostic information for sensitive information )

### Troubleshooting
* I tried to add IAM policy of "AmazonSSMReadOnlyAccess" to task execution role created by Cloud formation manually.
* Got it what I expect behavior as above.

### How to resolve this issue is below.
* Add "AmazonSSMReadOnlyAccess" and so on to [execution-role.yaml](https://github.com/newrelic/nri-ecs/blob/main/deploy/cloudformation/task/execution-role.yaml#L39) such as below.

```yaml
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AmazonEC2ContainerServiceforEC2Role"
        - "arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy"
        - "arn:aws:iam::aws:policy/AmazonSSMReadOnlyAccess" # Add this line.
        - !Ref NewRelicLicenseKeySecretReadAccess
```

## Steps to Reproduce
[NOTE]: # ( Please be as specific as possible. )
[TIP]:  # ( Link a sample application that demonstrates the issue. )

## Your Environment
[TIP]:  # ( Include as many relevant details about your environment as possible including the running version of New Relic software and any relevant configurations. )

I think resolve It  regardless of what type of environment.

## Additional context
[TIP]:  # ( Add any other context about the problem here. For example, relevant community posts or support tickets. )

nothing.

**Comment by davidgit** [comment]
This issue was closed because it has been inactive for a long time despite it can be reopened at any point if you think it still relevant.

Thank you for your contribution!
