### ISSUE TITLE
Release entries point to wrong tag for infrastructure bundle updates

### ISSUE THREAD

**Issue by ankon** [newrelic/nri-ecs#139]
^^ Provide a general summary of the issue in the title above. ^^ 

## Description

I'm reading the releases (https://github.com/newrelic/nri-ecs/releases), and then follow the links to the updates of the infrastructure bundle.

## Expected Behavior

Browser shows infrastructure bundle changelog.

## [Troubleshooting](https://discuss.newrelic.com/t/troubleshooting-frameworks/108787) or [NR Diag](https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/troubleshooting/new-relic-diagnostics) results

N/A

## Steps to Reproduce

Open https://github.com/newrelic/nri-ecs/releases, find infrastructure-bundle changelog links, click on them.

## Your Environment

A browser. :)

## Additional context

The links point to https://github.com/newrelic/infrastructure-bundle/releases/tag/3.2.13 (no "v"), they should point to https://github.com/newrelic/infrastructure-bundle/releases/tag/v3.2.13 ("v" before the version).

## For Maintainers Only or Hero Triaging this bug
*Suggested Priority (P1,P2,P3,P4,P5):*
*Suggested T-Shirt size (S, M, L, XL, Unknown):*

**Comment by marcsanmi** [comment]
Thanks for reporting it! We plan to do it as soon as possible.

Since the issue is related to the [release-toolkit](https://github.com/newrelic/release-toolkit), we've created this [issue](https://github.com/newrelic/release-toolkit/issues/174) to address it.

**Comment by paologallinaharbur** [comment]
Hello, I fixed the root cause, I'll edit the link on the releases already created, thanks again for reporting it
