### ISSUE TITLE
ARM Architecture Support

### ISSUE THREAD

**Issue by moustafaatefsaad** [newrelic/nri-ecs#140]
### Description
Supporting ARM architecture (Graviton)

### Acceptance Criteria
Building all the images that nri-ecs depends on with ARM and rebuilding the nri-ecs for ARM

### Describe Alternatives
I don't think there are any alternatives to make the amd x86 image work with an ARM architecture

### Dependencies
newrelic/infrastructure-bundle 

### Additional context
I'd like to use the newrelic nri-ecs with AWS Graviton2 Fargate as far as I'm concerned there is no image for nri-ecs build for ARM based architecture

### Estimates
M

**Comment by paologallinaharbur** [comment]
Hello, we are building already an arm image:
https://hub.docker.com/r/newrelic/nri-ecs/tags

Are you having issues with that?

**Comment by paologallinaharbur** [comment]
As you can see the pipeline is multiarc https://github.com/newrelic/nri-ecs/blob/9f06a8f5df0f26dad92b26b2443348872b6d0708/.github/workflows/release.yml#L16C7-L16C23
