### ISSUE TITLE
Improve tests with amazon/amazon-ecs-local-container-endpoints

### ISSUE THREAD

**Issue by paologallinaharbur** [newrelic/nri-ecs#24]
##Description
Currently there are not many unit/integration tests, we should improve them.

Note that there is an image `amazon/amazon-ecs-local-container-endpoints` that (maybe) can be used to have a local metadata endpoint

## Priority
Nice to Have

**Comment by paologallinaharbur** [comment]
After checking the code I noticed that in Dockerfile.debug such image is already used, but no test is automatized

**Comment by davidgit** [comment]
This issue was closed because it has been inactive for a long time despite it can be reopened at any point if you think it still relevant.

Thank you for your contribution!
