### ISSUE TITLE
Fargate Platform 1.4.0 Support

### ISSUE THREAD

**Issue by blytheaw** [newrelic/nri-ecs#3]
[NOTE]: # ( ^^ Provide a general summary of the request in the title above. ^^ )

## Summary

Fargate platform 1.4.0 has been recently released and supports a new range of network related metrics. It would be great to see these included in the New Relic solution for Fargate container monitoring.

## Desired Behaviour

This integration, when running on Fargate as a sidecar container, should send all metrics available on Fargate platform 1.4.0

## Possible Solution

Add support for the Task Metadata Endpoint v4 for deployments running on Fargate platform 1.4.0

## Additional context

We heavily use Fargate for our application deployments, and we use New Relic as our primary monitoring tool. However, it has been difficult to get detailed container-level metrics for things we care about. The v4 metadata endpoint for Fargate provides additional detail, such as network traffic statistics for containers. This would be really helpful to us.

**Comment by paologallinaharbur** [comment]
It is quite confusing, but nri-ecs is in charge only to fetch metadata regarding tasks, the metrics are scraped by nri-docker in the aws fargate package.

I bumped the metadata version on that repo and opened a PR
