### ISSUE TITLE
ECS training to Support

### ISSUE THREAD

**Issue by mangulonr** [newrelic/nri-ecs#33]
Suppport is asking for enablement for:

- Monitoring services on ECS: https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/monitor-services-running-amazon-ecs/.
- ECS integration which can be deployed through a Fargate or EC2 launch type: https://docs.newrelic.com/docs/integrations/elastic-container-service-integration/installation/install-ecs-integration/

We should create some documentation (maybe a PPT) to train support.

CAOS wants to collaborate with us, they need to know if they need to collaborate/contribute because the agent.
We need to update them  (José Moré) whenever we have the first version.

**Comment by gsanchezgavier** [comment]
[Slides](https://docs.google.com/presentation/d/1ePgQ9g3MqoAp7kTIgXTMFVAlw9eR8MOrAy1JD4q8Ouo/edit?usp=sharing)
