### ISSUE TITLE
Report Tasks Status

### ISSUE THREAD

**Issue by edevregille** [newrelic/nri-ecs#35]
## Feature Description
When using AWS Metric Stream, the ECS Tasks status are not in New Relic. So there is no way to know the running and pending tasks. The request is to have New Relic infra daemon to collect the status tasks out of the box.
There is maybe opportunity to collect more than the Tasks status (containers, services details).
https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_ListTasks.html

## Describe Alternatives
When doing the AWS Pull integration, we get the tasks status in the ComputeSample event. But the AWS Metric Stream is the recommended way to get the AWS metrics in New Relic.

## Priority
Really Want.

**Comment by mordamus** [comment]
Yeah, this would be awesome

**Comment by gsanchezgavier** [comment]
Hi @edevregille  thanks for submitting the FR. Are you monitoring the cluster using the [ECS integration](https://docs.newrelic.com/docs/integrations/elastic-container-service-integration/get-started/introduction-amazon-ecs-integration/) ?
