### ISSUE TITLE
Collect ClockDrift metadata block part of the new ${ECS_CONTAINER_METADATA_URI_V4}/task endpoint

### ISSUE THREAD

**Issue by tophercullen** [newrelic/nri-ecs#48]
Feature request to include the new `ClockDrift` metadata block which is part of the new v4 `${ECS_CONTAINER_METADATA_URI_V4}/task` endpoint

ClockDrift information is useful to determining if there's an time drift which can cause problems with time sensitive token/authorization flows.

Context: https://aws.amazon.com/about-aws/whats-new/2021/09/monitoring-clock-aws-fargate-amazon-ecs/

Priority:  Nice to have. Currently trying to troubleshoot an intermittent issue which may be due to clock drift.

**Comment by davidgit** [comment]
We appreciate you taking the time to bring this to our attention. After reviewing this issue, we are unable to commit on a timeline to resolution. When committing to resolve an issue, we take into account the type of issue, the customer impact, and the development effort required. If the situation changes, we will revisit this decision.

We encourage community contributions and are happy to collaborate on design proposals and pull requests. See our PR guidelines in the README. If you have any further questions or comments about this, please let us know by replying to this issue.
