### ISSUE TITLE
Missing attributes from the payload 

### ISSUE THREAD

**Issue by paologallinaharbur** [newrelic/nri-ecs#61]
I notice the three `ecsClusterName`, `ecsLaunchType` and `ecsClusterArn` disappearing. [Before](https://staging.onenr.io/0oqQaKZz5R1)->[After](https://staging.onenr.io/06vjAM9O3jP)

I believe that this is not expected.
I guess it is related to https://github.com/newrelic/nri-ecs/issues/30 and the NRIA_IS_FORWARD_ONLY change.
The solution should be  manually add those attributes to the ContainerSamples if the env is Fargate

**Comment by kang-makes** [comment]
For more info we dig during the pairing, [in the docs](https://docs.newrelic.com/docs/infrastructure/elastic-container-service-integration/understand-use-data/understand-use-ecs-data/#understand) we literally say:

> All the events reported from an ECS cluster contain the attributes ecsClusterName, ecsLaunchType and ecsClusterArn.
