### ISSUE TITLE
Document ECS event metadata

### ISSUE THREAD

**Issue by tscully49** [newrelic/nri-ecs#8]
## Is your feature request related to a problem? Please describe.
No

## Feature Description
It would be helpful to have a documented chart of data that is gathered from ECS Hosts/Fargate in order to know exactly what data is exported.  

## Additional context
Might be advantageous to also document here: https://docs.newrelic.com/docs/integrations/elastic-container-service-integration/understand-use-data/ecs-integration-understand-use-data

## Priority
Please help us better understand this feature request by choosing a priority from the following options: 
[Nice to Have, Really Want, Must Have, Blocker] 

Nice to Have

**Comment by gsanchezgavier** [comment]
Hi @tscully49 this integration by itself is not reporting any metrics. Just the cluster metadata that is used to decorate all metrics reported by the infra agent, docker integration, and the other on host integrations if they are activated.
You can find the details on [this section](https://docs.newrelic.com/docs/infrastructure/elastic-container-service-integration/understand-use-data/understand-use-ecs-data/#understand).
