### ISSUE TITLE
Task tags not included in exported data

### ISSUE THREAD

**Issue by jlsalmon** [newrelic/nri-ecs#91]
## Description
When browsing the ContainerSample event data that results from this integration, the tags attached to the ECS tasks are not propagated to NR.

## Expected Behaviour
Task tags are exported to and queryable in NR.

## Your Environment
Fargate containers running latest nri-ecs sidecar.

## Additional context
I believe that the `${ECS_CONTAINER_METADATA_URI_V4}/taskWithTags` endpoint should be used to achieve this.

**Comment by davidgit** [comment]
Hi,

We consolidated multiple channels that were used to file Feature Requests (FRs). In the spirit of improving the visibility of FRs, we believe it's best for them to be submitted through the [New Relic Issue Tracker](https://issues.newrelic.com). This single tool will enable better aggregation of FRs and improve our ability to synthesize requests and provide better value to our users. You can see and vote for other FRs submitted by all users.

Please provide a link to this GitHub issue when submitting your feature request.

Thanks!
